student_count = 25
#first we're gonna print the students' names
puts "The students of my cohort at Makers Academy"
puts "-----------------"
puts "Dave"
puts "Eddie"
puts "Catharina"
puts "Igor"
puts "Marco"
puts "Lisa"
puts "Michiel"
puts "Jean"
puts "Nicola"
puts "Jenny"
puts "Iona"
puts "Nikesh"
puts "Chloe"
puts "Toan"
puts "Jamie"
puts "Peter"
puts "Talal"
puts "Charlie"
puts "Charlotte"
puts "Thomas"
puts "Zoe"
puts "Hannah"
puts "Joe"
puts "Alex"
puts "Jeremy"

#finally, we print the total
print "Overall, we have #{student_count} great students"

